aws_region = "us-west-2"
aws_access_key = "AKIAI6CDST2JX7IZLLSQ"
aws_secret_key = "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"
instance_type = "m3.medium"
key_name = "aws-ssh-key"
key_file_name = "aws-ssh-key.pem"
instance_name = "terraform-test-instance"
subnet_id = "subnet-0438095d"
